services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
    ports:
      - 5433:5432
    env_file:
      - .env
  redis:
    image: redis:latest
    ports:
      - 6379:6379
